module FileSystemApp
{
typedef sequence<octet> byteSeq;
  interface FileSystem
  {
  string sayHello();
  string readFile(in string title);
  oneway void shutdown();
  string openFileLineNumber(in string title, in short lineNum);
  };
};
