module FileSystemApp
{
typedef sequence<octet> byteSeq;
  interface FileSystem
  {
  string sayHello();
  string readFile(in string title);
  oneway void shutdown();
  
  string openFileForRead(in string title);
  string openFileForWrite(in string title);

  string closeRead(in string title);
  string closeWrite(in string title, in string newContents);

  boolean createLocalFile(in string title, in short amntPplRead, in short verNo);
  string updateLocalFile(in string title, in string newContents);
  string lockForWrite(in string title);
  string unlockLocally(in string title);

  string startReadLocally(in string title);
  string stopReadLocally(in string title);

  string retreiveInfo(in string title);
  };
};
