package FileSystemApp;


/**
* FileSystemApp/FileSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, November 29, 2020 at 10:45:46 AM Eastern Standard Time
*/

public interface FileSystem extends FileSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSystem
