package FileSystemApp;


/**
* FileSystemApp/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Tuesday, December 1, 2020 at 11:26:27 AM Eastern Standard Time
*/

public interface FileSystemOperations 
{
  String sayHello ();
  String readFile (String title);
  void shutdown ();
  String openFileLineNumber (String title, short lineNum);
  String openFileForWrite (String title, short linenum);
  String updateFileAfterWrite (String newLine, String title, short lineNum);
} // interface FileSystemOperations
