package FileSystemApp;


/**
* FileSystemApp/FileSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Thursday, December 3, 2020 3:46:40 PM EST
*/

public abstract class FileSystemPOA extends org.omg.PortableServer.Servant
 implements FileSystemApp.FileSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("readFile", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
    _methods.put ("openFileForRead", new java.lang.Integer (3));
    _methods.put ("openFileForWrite", new java.lang.Integer (4));
    _methods.put ("closeRead", new java.lang.Integer (5));
    _methods.put ("closeWrite", new java.lang.Integer (6));
    _methods.put ("lockForWrite", new java.lang.Integer (7));
    _methods.put ("unlockLocally", new java.lang.Integer (8));
    _methods.put ("stopReadLocally", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FileSystemApp/FileSystem/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FileSystemApp/FileSystem/readFile
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.readFile (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FileSystemApp/FileSystem/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 3:  // FileSystemApp/FileSystem/openFileForRead
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.openFileForRead (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FileSystemApp/FileSystem/openFileForWrite
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.openFileForWrite (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // FileSystemApp/FileSystem/closeRead
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.closeRead (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FileSystemApp/FileSystem/closeWrite
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.closeWrite (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // FileSystemApp/FileSystem/lockForWrite
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.lockForWrite (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // FileSystemApp/FileSystem/unlockLocally
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.unlockLocally (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // FileSystemApp/FileSystem/stopReadLocally
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.stopReadLocally (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FileSystemApp/FileSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileSystem _this() 
  {
    return FileSystemHelper.narrow(
    super._this_object());
  }

  public FileSystem _this(org.omg.CORBA.ORB orb) 
  {
    return FileSystemHelper.narrow(
    super._this_object(orb));
  }


} // class FileSystemPOA
