package FileSystemApp;


/**
* FileSystemApp/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sunday, December 6, 2020 at 7:43:31 PM Eastern Standard Time
*/

public interface FileSystemOperations 
{
  String sayHello ();
  String readFile (String title);
  void shutdown ();
  String openFileForRead (String title);
  String openFileForWrite (String title);
  String closeRead (String title);
  String closeWrite (String title, String newContents);
  boolean createLocalFile (String title, short amntPplRead, short verNo);
  String updateLocalFile (String title, String newContents);
  String lockForWrite (String title);
  String unlockLocally (String title);
  String startReadLocally (String title);
  String stopReadLocally (String title);
  String retreiveInfo (String title);
} // interface FileSystemOperations
