package FileSystemApp;


/**
* FileSystemApp/FileSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Tuesday, December 1, 2020 at 11:26:27 AM Eastern Standard Time
*/

public interface FileSystem extends FileSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSystem
