package FileSystemApp;

/**
* FileSystemApp/SomethingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Thursday, December 3, 2020 1:13:50 PM EST
*/

public final class SomethingHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystemApp.Something value = null;

  public SomethingHolder ()
  {
  }

  public SomethingHolder (FileSystemApp.Something initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.SomethingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.SomethingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.SomethingHelper.type ();
  }

}
