package TarynsCoolApp;


/**
* TarynsCoolApp/byteSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Thursday, December 3, 2020 1:05:27 PM EST
*/

public final class byteSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public byteSeqHolder ()
  {
  }

  public byteSeqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TarynsCoolApp.byteSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TarynsCoolApp.byteSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TarynsCoolApp.byteSeqHelper.type ();
  }

}
