package TarynsCoolApp;

/**
* TarynsCoolApp/SomethingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Thursday, December 3, 2020 1:05:27 PM EST
*/

public final class SomethingHolder implements org.omg.CORBA.portable.Streamable
{
  public TarynsCoolApp.Something value = null;

  public SomethingHolder ()
  {
  }

  public SomethingHolder (TarynsCoolApp.Something initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TarynsCoolApp.SomethingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TarynsCoolApp.SomethingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TarynsCoolApp.SomethingHelper.type ();
  }

}
