package TarynsCoolApp;


/**
* TarynsCoolApp/SomethingPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Thursday, December 3, 2020 1:05:27 PM EST
*/

public abstract class SomethingPOA extends org.omg.PortableServer.Servant
 implements TarynsCoolApp.SomethingOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("lockForWrite", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TarynsCoolApp/Something/lockForWrite
       {
         String title = in.read_string ();
         String $result = null;
         $result = this.lockForWrite (title);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TarynsCoolApp/Something:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Something _this() 
  {
    return SomethingHelper.narrow(
    super._this_object());
  }

  public Something _this(org.omg.CORBA.ORB orb) 
  {
    return SomethingHelper.narrow(
    super._this_object(orb));
  }


} // class SomethingPOA
