package TarynsCoolApp;


/**
* TarynsCoolApp/SomethingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Thursday, December 3, 2020 1:05:27 PM EST
*/

public interface SomethingOperations 
{
  String lockForWrite (String title);
} // interface SomethingOperations
